### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by EdwinWenink** [dex-ethics/open-eth#25]
Hi there, I was curious about this project, but it doesn't seem to be maintained anymore and openeth.com seems to be offline. Is this project abandoned?

**Comment by NellInc** [comment]
Hi Edwin,

OpenEth.org (Now EthicsNet.org) is still very much alive, and this legacy implementation is accessible at http://legacy.ethicsnet.org/

I hope that this helps. Thank you.

–Nell Watson

**Comment by EdwinWenink** [comment]
Thanks for the fast response. I see, that's good to hear! In case you care about replacing the dead link, I made a quick PR #26 that points to the new domain. Just to help lost souls ;-)

**Comment by NellInc** [comment]
Thanks, Edwin! Much appreciated! :D
